### PR TITLE
Fix tab key handling

### LINKED ISSUE #71: Tab key support is broken
Support for typing tab characters in the textarea was introduced all the way back in d2549d0efdd9efa05f76d98cd7e8163c29194a99, but it stopped working along the way, as @SenadAlagic pointed out in #70.

I've bisected the faulty change to commit 2e55678411bf267638240960732f796a7682dc61, which implemented the auto-save functionality. We need to restore the tab key functionality without messing with the auto-save.

### PR DESCRIPTION
**Pull request by SenadAlagic**
I merged the two functions, one for tab indentation and one for autosaving. This seems to work, hopefully this is the implementation you'll be happy with! Cheers!

Fixes #71

### CODE REVIEW

**Comment by SenadAlagic** [comment]
I see again that there are merge conflicts. This is not the same situation as it was last time? Or do I need to rebase and handle these conflicts myself? Thanks!

File: script.js [hunk 1]
```diff
@@ -9,18 +9,15 @@ calcStats(); // Update counters after loading
 function storeLocally() { localStorage.setItem('browserpad', textbox.value); }
 window.beforeunload = storeLocally;
 
-// Allow inputting tabs in the textarea instead of changing focus to the next element
-textbox.onkeypress = function (event) {
-    if (event.keyCode === 9) {
-        event.preventDefault();
+// Auto-save to local storage and calculate stats on every keystroke
+textbox.onkeydown = function (e) {
```
Comment (waldyrious) [inline script.js:13]: Doesn't `onkeydown` trigger repeatedly if you keep the key pressed down? If so, we'll probably need to use `onkeyup` or `onkeypress` instead to avoid that.

File: script.js [hunk 2]
```diff
@@ -9,18 +9,15 @@ calcStats(); // Update counters after loading
...
 window.beforeunload = storeLocally;
 
-// Allow inputting tabs in the textarea instead of changing focus to the next element
-textbox.onkeypress = function (event) {
-    if (event.keyCode === 9) {
-        event.preventDefault();
+// Auto-save to local storage and calculate stats on every keystroke
+textbox.onkeydown = function (e) {
+    if(e.keyCode==9)
+    {
```
Comment (waldyrious) [inline script.js:15]: Why did you move this bracket to a new line?

File: script.js [hunk 3]
```diff
@@ -9,18 +9,15 @@ calcStats(); // Update counters after loading
 function storeLocally() { localStorage.setItem('browserpad', textbox.value); }
 window.beforeunload = storeLocally;
 
-// Allow inputting tabs in the textarea instead of changing focus to the next element
```
Comment (waldyrious) [inline script.js:12]: This comment should be preserved above the tab-processing code.

Comment (SenadAlagic) [reply script.js:12]: Will bring it back. Thank you for pointing that out.

File: script.js (hunk 1 above)
Comment (SenadAlagic) [reply script.js:13]: For some reason onkeydown is the only one that works. Neither the onkeyup or the onkeypress work, at all. Not sure what's causing it but yes, my original intent was to make it with onkeypress0. The onkeydown does fire repeteadly though. Any ides as to how we can improve it?

File: script.js (hunk 2 above)
Comment (SenadAlagic) [reply script.js:15]: That's usually how I do it, for my own visibility I guess. Doesn't _really_ matter to me so I'll bring it up.

File: script.js (hunk 1 above)
Comment (waldyrious) [reply script.js:13]: I don't really know what might be the issue here, sorry. Perhaps StackOverflow might have some answers?

Comment (SenadAlagic) [reply script.js:13]: From a quick glance it found this: 

>onkeypress is only triggered for the 'active' field when a key is pressed.
The clue there is the word 'field' -- by default, <div> elements cannot become 'active'; only input fields.

It's late so I will definitely look into this better tomorrow but I have some ideas we could implement. Thanks for the tip!

**Comment by SenadAlagic** [comment]
Hey, just checking up on you. Hopefully you're okay and just busy so you can't respond. I'm ready to continue working whenever you give me the heads up 😄

**Comment by waldyrious** [comment]
@SenadAlagic I am so sorry for my lack of response! :broken_heart: I haven't been able to properly maintain my projects and this is totally unfair for contributors. All is good with me, just busier now that I'm a father of two young kids :)

I realize this branch is now conflicted due to my merge of another PR. I'll go ahead and rebase it to fix the conflicts, and hopefully merge it afterwards.

**Comment by waldyrious** [comment]
@SenadAlagic I actually ended up going with a different approach. I kept the two functions separate, as merging them did not fix this bug, and in fact would have (re)introduced a subtler one that was fixed all the way back in caa8861db0265c8209663afecd826c01c92d6f4c. I added code comments to explain the choices of both `onkeydown` and `onkeyup`.

Thanks again for tackling this and leading the way towards a fix! Merging now.

**Comment by SenadAlagic** [comment]
> @SenadAlagic I am so sorry for my lack of response! 💔 I haven't been able to properly maintain my projects and this is totally unfair for contributors. All is good with me, just busier now that I'm a father of two young kids :)
> 
> I realize this branch is now conflicted due to my merge of another PR. I'll go ahead and rebase it to fix the conflicts, and hopefully merge it afterwards.

Hello! Glad to see you're back. Absolutely no need to apologize for spending time with your family. I've been absent from this project for *quite* a while, and I'd like to think I'm more experienced now. If you'd like we can continue working on this, whatever issue or feature you'd like we can surely make it.
